"""SQL safety validation. No exec(), no eval(), no mutations.

This is the single most important module in the project. Every query
generated by the LLM passes through here before touching the database.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class RiskLevel(Enum):
    SAFE = "safe"
    SUSPICIOUS = "suspicious"
    BLOCKED = "blocked"


@dataclass
class SafetyVerdict:
    level: RiskLevel
    sql: str
    reason: Optional[str] = None

    @property
    def is_allowed(self) -> bool:
        return self.level in (RiskLevel.SAFE, RiskLevel.SUSPICIOUS)

    @property
    def is_safe(self) -> bool:
        return self.level == RiskLevel.SAFE


# ── Blocked patterns: NEVER execute ─────────────────────────────────
_BLOCKED_PATTERNS: list[tuple[str, str]] = [
    # DDL
    (r"\b(CREATE|ALTER|DROP|TRUNCATE|RENAME)\b", "DDL statement"),
    # DML mutations
    (r"\b(INSERT|UPDATE|DELETE|MERGE|REPLACE)\b", "data mutation"),
    # Privileges
    (r"\b(GRANT|REVOKE|DENY)\b", "privilege command"),
    # Procedure / script execution
    (r"\b(EXEC|EXECUTE)\s", "procedure execution"),
    (r"\bCALL\s", "procedure call"),
    # Exasol scripting
    (r"\bCREATE\s+(OR\s+REPLACE\s+)?(LUA|PYTHON|JAVA|R)\s+SCRIPT\b", "script creation"),
    (r"\bEXPORT\b", "EXPORT statement"),
    (r"\bIMPORT\b", "IMPORT statement"),
    # DuckDB-specific dangerous operations
    (r"\bCOPY\b", "COPY statement"),
    (r"\bATTACH\b", "ATTACH database"),
    (r"\bDETACH\b", "DETACH database"),
    (r"\bINSTALL\b", "INSTALL extension"),
    (r"\bLOAD\b", "LOAD extension/data"),
    (r"\bPRAGMA\b", "PRAGMA command"),
    (r"\bCHECKPOINT\b", "CHECKPOINT command"),
    (r"\bVACUUM\b", "VACUUM command"),
    (r"\bFORCE\s+CHECKPOINT\b", "FORCE CHECKPOINT"),
    # File access
    (r"\bINTO\s+(OUTFILE|DUMPFILE)\b", "file write"),
    (r"\bread_csv\s*\(", "read_csv file access"),
    (r"\bread_parquet\s*\(", "read_parquet file access"),
    (r"\bread_json\s*\(", "read_json file access"),
    (r"\bread_csv_auto\s*\(", "read_csv_auto file access"),
    # Shutdown / kill
    (r"\bSHUTDOWN\b", "shutdown command"),
    (r"\bKILL\b", "kill command"),
    # Time-delay injection
    (r"\bpg_sleep\b", "pg_sleep injection"),
    (r"\bwaitfor\s+delay\b", "WAITFOR delay injection"),
    (r"\bbenchmark\s*\(", "BENCHMARK injection"),
    (r"\bdbms_lock\.sleep\b", "DBMS_LOCK.SLEEP injection"),
    # Statement stacking (semicolon followed by another statement)
    (r";\s*(SELECT|INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|EXEC|EXECUTE|CALL|EXPORT|IMPORT|COPY|ATTACH|LOAD|INSTALL|PRAGMA)",
     "statement stacking"),
    # SET commands (except SET TRANSACTION READ ONLY which we use internally)
    (r"\bSET\s+(?!TRANSACTION\s+READ\s+ONLY)", "SET command"),
]

# ── Suspicious patterns: execute with warning ────────────────────────
_SUSPICIOUS_PATTERNS: list[tuple[str, str]] = [
    (r"\bUNION\s+(ALL\s+)?SELECT\b", "UNION injection pattern"),
    (r"\bOR\s+1\s*=\s*1\b", "tautology (OR 1=1)"),
    (r"\bOR\s+['\"].*?['\"]\s*=\s*['\"]", "string tautology injection"),
    (r"\bINFORMATION_SCHEMA\b", "information_schema access"),
    (r"\bSYS\.\b", "SYS schema access"),
    (r"\bEXA_\w+", "Exasol system table access"),
    (r"\bduckdb_\w+\s*\(", "DuckDB internal function"),
    (r"\bpg_catalog\b", "pg_catalog access"),
]


def validate_sql(
    sql: str,
    allowed_schemas: Optional[set[str]] = None,
    allowed_tables: Optional[set[str]] = None,
) -> SafetyVerdict:
    """Validate generated SQL is safe to execute.

    Args:
        sql: The SQL string to validate.
        allowed_schemas: If set, only these schemas may appear in FROM/JOIN.
        allowed_tables: If set, only these tables may appear in FROM/JOIN.

    Returns:
        SafetyVerdict with risk level and reason.
    """
    if not sql or not sql.strip():
        return SafetyVerdict(RiskLevel.BLOCKED, sql, "empty query")

    normalized = sql.strip()

    # ── Must start with SELECT or WITH (CTE) ─────────────────────
    if not re.match(r"^\s*(SELECT|WITH)\b", normalized, re.IGNORECASE):
        return SafetyVerdict(
            RiskLevel.BLOCKED, sql, "query must start with SELECT or WITH"
        )

    # ── Check blocked patterns ───────────────────────────────────
    for pattern, reason in _BLOCKED_PATTERNS:
        if re.search(pattern, normalized, re.IGNORECASE):
            return SafetyVerdict(RiskLevel.BLOCKED, sql, reason)

    # ── Multiple statements ──────────────────────────────────────
    stripped = normalized.rstrip(";").strip()
    if ";" in stripped:
        return SafetyVerdict(RiskLevel.BLOCKED, sql, "multiple statements detected")

    # ── Schema/table allowlist enforcement ───────────────────────
    if allowed_schemas or allowed_tables:
        violation = _check_object_access(normalized, allowed_schemas, allowed_tables)
        if violation:
            return SafetyVerdict(RiskLevel.BLOCKED, sql, violation)

    # ── Check suspicious patterns ────────────────────────────────
    for pattern, reason in _SUSPICIOUS_PATTERNS:
        if re.search(pattern, normalized, re.IGNORECASE):
            return SafetyVerdict(RiskLevel.SUSPICIOUS, sql, reason)

    return SafetyVerdict(RiskLevel.SAFE, sql)


def _check_object_access(
    sql: str,
    allowed_schemas: Optional[set[str]],
    allowed_tables: Optional[set[str]],
) -> Optional[str]:
    """Check that only allowed schemas/tables appear in FROM and JOIN clauses.

    Handles both unquoted (FROM orders) and double-quoted (FROM "orders")
    identifiers, as well as schema-qualified refs (FROM sales.orders or
    FROM "sales"."orders").
    """
    # Each identifier is either "quoted" or unquoted_word
    _ident = r'"[^"]*"|[A-Za-z_]\w*'
    # Full ref: ident or ident.ident
    _ref   = rf'({_ident})(?:\.({_ident}))?'
    # Must follow FROM / JOIN keyword + whitespace
    pattern = re.compile(
        rf'(?:FROM|JOIN)\s+{_ref}(?=\s|,|\)|$)',
        re.IGNORECASE,
    )

    def _bare(tok: Optional[str]) -> str:
        """Strip surrounding double-quotes and uppercase."""
        if not tok:
            return ""
        return tok.strip('"').upper()

    for m in pattern.finditer(sql):
        first, second = m.group(1), m.group(2)

        if second:
            # schema.table form
            schema = _bare(first)
            table  = _bare(second)
            if allowed_schemas and schema not in {s.upper() for s in allowed_schemas}:
                return f"schema '{schema}' not in allowed list"
            if allowed_tables and table not in {t.upper() for t in allowed_tables}:
                return f"table '{schema}.{table}' not in allowed list"
        else:
            # bare table form
            table = _bare(first)
            if allowed_tables and table not in {t.upper() for t in allowed_tables}:
                return f"table '{table}' not in allowed list"

    return None


def sanitize_sql(sql: str) -> str:
    """Strip comments and normalize whitespace without changing semantics.

    Order matters: strip comments before collapsing whitespace, otherwise a
    single-line -- comment eats everything that follows on the same line after
    newlines are collapsed.
    """
    sql = sql.strip().rstrip(";").strip()
    # Remove /* ... */ block comments
    sql = re.sub(r"/\*.*?\*/", "", sql, flags=re.DOTALL)
    # Remove -- single-line comments (to end of line, preserving the newline)
    sql = re.sub(r"--[^\n]*", "", sql)
    # Normalize: strip each line, drop blank lines, rejoin
    lines = [ln.strip() for ln in sql.splitlines() if ln.strip()]
    return "\n".join(lines)
